targetNameSpaces:
  - name: "openshift-ptp"

targetPodLabels:
  - prefix: redhat-best-practices-for-k8s.com
    name: generic
    value: target

targetOperatorLabels:
  - prefix: redhat-best-practices-for-k8s.com
    name: operator
    value: target

targetCrdFilters:
  - nameSuffix: "ptp.openshift.io"
    scalable: false
